name: Documentation update checker
on:
  pull_request:
    types: [opened]
    paths:
     - 'deploy/Kubernetes/**'
     - '**/*.md'
     - 'CODEOWNERS'
jobs:
  pr_reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Skipping full CI for documentation
        uses: actions/github-script@v7
        env:
          REPOSITORY: ${{ github.repository }}
          CONTRIBUTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const { REPOSITORY, CONTRIBUTOR } = process.env

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `ðŸ‘‹ Hi ${CONTRIBUTOR}! Thank you for contributing to ${REPOSITORY}.\n\n` +
                `This change is made to a file that does not require full CI testing. A repository admin will review these changes.\n\n` +
                `Once verified, the reviewer will merge the PR. Thanks! \n\n` +
                `ðŸš€`
            })
      - name: Adding Label
        uses: actions/github-script@v7
        env:
          REPOSITORY: ${{ github.repository }}
          CONTRIBUTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const { REPOSITORY, CONTRIBUTOR } = process.env

            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ["documentation"]
            });
